[package]
name = "cidr"
version = "0.1.1"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
env_logger = "0.11.8"
eyre = "0.6.12"
ipnetwork = "0.21.1"
lazy_static = "1.5.0"
log = "0.4.27"
